### ISSUE TITLE
couldn't load pretrained gpt2

### ISSUE THREAD

**Issue by DeepInEvil** [simonepri/lm-scorer#9]
It gives an error while loading gpt2
File "/home/debanjan/anaconda3/envs/py_3/lib/python3.7/site-packages/lm_scorer/models/gpt2.py", line 84, in _supported_model_names
    return GPT2LMHeadModel.pretrained_model_archive_map.keys()
AttributeError: type object 'GPT2LMHeadModel' has no attribute 'pretrained_model_archive_map'

can you kindly check?

**Comment by simonepri** [comment]
Thanks for reporting, I'll have a look.

**Comment by simonepri** [comment]
Fixed in [v0.4.2](https://github.com/simonepri/lm-scorer/releases/tag/v0.4.2).

Apparently they removed the `pretrained_model_archive_map` in https://github.com/huggingface/transformers/pull/4152.

Thanks for reporting!
